spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'peneksoft@gmail.com'
    password: 'roqxrsaenjwefeup'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://211.42.156.199/shift3?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC"
    username: "root"
    password: "shift32022@"
  jpa:
    database: mysql
    hibernate:
      driverClassName: com.mysql.cj.jdbc.Driver
      dialect: com.sch.shift3.config.CustomDialect
      ddl-auto: none #create update none
      format_sql: true
      use_sql_comment: true
      jdbc:
        time_zone: UTC
    show-sql: true
  # file upload max size (파일 업로드 크기 설정)
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    livereload:
      enable: true
  thymeleaf:
    cache: false
    mode: "HTML"
    check-template-location: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c9c99f2b755d05ff320b48f64b530849
            client-secret: 10b4089090b3c8756eb564cabf6e1c81
            redirect-uri: http://shift3.kr/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
            client-name: kakao
            client-authentication-method: POST
          naver:
            client-id: sAcKuXt60ESOGETn6xtp
            client-secret: QK7mKWNgUF
            redirect-uri: http://shift3.kr/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: nickname,email,name
            client-name: Naver
          facebook:
            client-id: 1255723775019147
            client-secret: 5eb9a9593cd1515126638fc2562a6098
            redirect-uri: http://shift3.kr/login/oauth2/code/facebook
            authorization-grant-type: authorization_code
            scope: email
            client-name: Facebook


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          facebook:
            authorization-uri: https://www.facebook.com/v3.3/dialog/oauth
            token-uri: https://graph.facebook.com/v3.3/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email
            user-name-attribute: id
            client-authentication-method: post



server:
  port: 8080



