spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'peneksoft@gmail.com'
    password: 'roqxrsaenjwefeup'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://211.42.156.199/shift3?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC"
    username: "root"
    password: "shift32022@"
  jpa:
    database: mysql
    hibernate:
      driverClassName: com.mysql.cj.jdbc.Driver
      dialect: com.sch.shift3.config.CustomDialect
      ddl-auto: none #create update none
      format_sql: true
      use_sql_comment: true
      jdbc:
        time_zone: UTC
    show-sql: true
  # file upload max size (파일 업로드 크기 설정)
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  devtools:
    livereload:
      enable: true
  thymeleaf:
    cache: false
    mode: "HTML"
    check-template-location: true
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080



